apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: packmate-frontend
  labels:
    app.kubernetes.io/name: packmate-frontend
    app.kubernetes.io/component: frontend
spec:
  to:
    kind: Service
    name: packmate-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
