apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: packmate-backend
      app.kubernetes.io/component: backend
    includeSelectors: true
