apiVersion: v1
kind: ServiceAccount
metadata:
  name: packmate-backend
  labels:
    app.kubernetes.io/name: packmate-backend
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
