apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: packmate-lab
resources:
- ../../base
images:
- name: quay.io/example/packmate-backend
  newName: image-registry.openshift-image-registry.svc:5000/packmate-lab/packmate-backend
  digest: sha256:c057f9f17546a3f144a60bf5b43a15c3ead0f9841663d53c52ee81948a29c1e6
- name: quay.io/example/packmate-frontend
  newName: image-registry.openshift-image-registry.svc:5000/packmate-lab/packmate-frontend
  digest: sha256:cdf68e4b6d5f9393f747e430e9a432ec352fbe17b61eddb65cce9d3037b7b3e7
- name: quay.io/example/packmate-weather-mcp
  newName: image-registry.openshift-image-registry.svc:5000/packmate-lab/packmate-weather-mcp
  digest: sha256:4ddce548b9077d59f380c48f1d3c7fac6917a83d1e77636e8bc8bc4f498518dc
- name: quay.io/example/packmate-baggage-policy-mcp
  newName: image-registry.openshift-image-registry.svc:5000/packmate-lab/packmate-baggage-policy-mcp
  digest: sha256:005d4ccdcc2c06afdc545e4e6ff0d5b3fc02fd4f349e1287253efe7e44036458
patches:
- path: configmap-patch.yaml
