apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - oauth-proxy-configmap.yaml
  - oauth-proxy-service.yaml
  - oauth-proxy-deployment.yaml
  - oauth-proxy-route.yaml

patches:
  - path: hide-frontend-route.yaml
