# ─── 1. LE SERVICE (Le standardiste réseau) ──────────────────
apiVersion: v1
kind: Service
metadata:
  name: packmate-agent-git
  namespace: packmate-agent-prod
spec:
  selector:
    app: packmate-agent-git
  ports:
    - name: http-streamlit
      port: 8080
      targetPort: 8080
---
# ─── 2. LA ROUTE (L'accès public internet) ───────────────────
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: packmate-agent-git
  namespace: packmate-agent-prod
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: packmate-agent-git
---
# ─── 3. LE DEPLOYMENT (Ton application) ───────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packmate-agent-git
  namespace: packmate-agent-prod
  annotations:
    # Ce bloc surveille l'image en DEV et met à jour la PROD automatiquement
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "packmate-agent-git:latest",
            "namespace": "packmate-agent"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"packmate-agent-git\")].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packmate-agent-git
  template:
    metadata:
      labels:
        app: packmate-agent-git
    spec:
      containers:
        - name: packmate-agent-git
          # L'URL du registre interne que nous avons validée ensemble
          image: "image-registry.openshift-image-registry.svc:5000/packmate-agent/packmate-agent-git:latest"
          imagePullPolicy: Always
          ports:
            - name: http-streamlit
              containerPort: 8080
          env:
            - name: LITELLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: packmate-secrets
                  key: LITELLM_API_KEY
            - name: BASE_URL
              value: "https://litellm-prod.apps.maas.redhatworkshops.io/v1"
            - name: MODEL
              value: "llama-scout-17b"
