# ─── 1. LE SERVICE (Réseau interne) ──────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: packmate-agent-git
spec:
  selector:
    app: packmate-agent-git
  ports:
    - port: 8080
      targetPort: 8080

---
# ─── 2. LA ROUTE (URL Publique) ──────────────────────────────
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: packmate-agent-git
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: packmate-agent-git

---
# ─── 3. LE DEPLOYMENT (Le Conteneur sécurisé) ────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packmate-agent-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packmate-agent-git
  template:
    metadata:
      labels:
        app: packmate-agent-git
    spec:
      containers:
        - name: packmate-agent-git
          image: "image-registry.openshift-image-registry.svc:5000/packmate-agent/packmate-agent-git@sha256:7396462755f1d2bedede6ddf6f22474915edc262d4004ae91d4aedef24d3e533"
          ports:
            - containerPort: 8080
          # Injection de la clé API depuis le Secret OpenShift
          env:
            - name: LITELLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: packmate-secrets
                  key: LITELLM_API_KEY