apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - backend
  - frontend

labels:
  - pairs:
      app.kubernetes.io/part-of: packmate
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
